
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.business.dto

#??????

spring:
  datasource:
    username: root
    password: sasa
    url: jdbc:mysql://localhost:3306/ssm
    driver-class-name: com.mysql.cj.jdbc.Driver

